# Install Libraries

In [42]:
import pandas as pd
import os

# Read Geospatial data

In [43]:
# Geospatial_Coordinates provided in the instruction
lonlat=pd.read_csv('E:\\Saurav\\LAPPY\\study\\Coursera\\IBM_Data_Science\\project\\IBM_DATA_SCIENCE\\week_3\\Geospatial_Coordinates.csv')

# Toronto table created in task 1
trt=pd.read_csv('E:\\Saurav\\LAPPY\\study\\Coursera\\IBM_Data_Science\\project\\IBM_DATA_SCIENCE\\week_3\\week_3_task_2.csv')

In [44]:
trt

,PostalCode,Borough,Neighborhood2,Neighborhood
0,M1B,Scarborough,"Malvern, Rouge","Malvern, Rouge"
1,M1C,Scarborough,"Rouge Hill, Port Union, Highland Creek","Rouge Hill, Port Union, Highland Creek"
2,M1E,Scarborough,"Guildwood, Morningside, West Hill","Guildwood, Morningside, West Hill"
3,M1G,Scarborough,Woburn,Woburn
4,M1H,Scarborough,Cedarbrae,Cedarbrae
...,...,...,...,...
98,M9N,York,Weston,Weston
99,M9P,Etobicoke,Westmount,Westmount
100,M9R,Etobicoke,"Kingsview Village, St. Phillips, Martin Grove ...","Kingsview Village, St. Phillips, Martin Grove ..."
101,M9V,Etobicoke,"South Steeles, Silverstone, Humbergate, Jamest...","South Steeles, Silverstone, Humbergate, Jamest..."
102,M9W,Etobicoke,Northwest,Northwest

# Merging Data

In [45]:
# Change the name "Postal Code" in lonlat to "PostalCode"
lonlat.rename(columns={'Postal Code':'PostalCode'},inplace=True)

# Left join
trt_geo=pd.merge(trt,lonlat,how='left',on='PostalCode')
trt_geo.drop(columns='Neighborhood2',inplace=True)

# Export the table

In [46]:
# Export trt_geo for the preparation of Task 3
trt_geo.to_csv(r'E:\\Saurav\\LAPPY\\study\\Coursera\\IBM_Data_Science\\project\\IBM_DATA_SCIENCE\\week_3\\week_3_task_3.csv',index=None,header=True)

In [47]:
trt_geo

,PostalCode,Borough,Neighborhood,Latitude,Longitude
0,M1B,Scarborough,"Malvern, Rouge",43.806686,-79.194353
1,M1C,Scarborough,"Rouge Hill, Port Union, Highland Creek",43.784535,-79.160497
2,M1E,Scarborough,"Guildwood, Morningside, West Hill",43.763573,-79.188711
3,M1G,Scarborough,Woburn,43.770992,-79.216917
4,M1H,Scarborough,Cedarbrae,43.773136,-79.239476
...,...,...,...,...,...
98,M9N,York,Weston,43.706876,-79.518188
99,M9P,Etobicoke,Westmount,43.696319,-79.532242
100,M9R,Etobicoke,"Kingsview Village, St. Phillips, Martin Grove ...",43.688905,-79.554724
101,M9V,Etobicoke,"South Steeles, Silverstone, Humbergate, Jamest...",43.739416,-79.588437
102,M9W,Etobicoke,Northwest,43.706748,-79.594054

In [49]:
trt_geo.shape

(103, 5)